stages:
  - triggers

backend:
  stage: triggers
  trigger:
    include: backend/backend-gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - backend/**/*
        - .gitlab-ci.yml

frontend:
  stage: triggers
  trigger:
    include: frontend/frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - frontend/**/*
        - .gitlab-ci.yml
