stages:
  - build
  - deploy

backend-build:
  stage: build
  trigger:
    include: backend/backend-gitlab-ci.yml
    strategy: depend
  only:
    - main

frontend-build:
  stage: build
  trigger:
    include: frontend/frontend/.gitlab-ci.yml
    strategy: depend
  only:
    - main
