services:
  backend:
    image: gitlab.thompson.uz:5050/finance/backend:main  # ✅ Pull from registry
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    volumes:
      - uploads_data:/app/uploads
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - UPLOAD_DIR=/app/uploads
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    image: gitlab.thompson.uz:5050/finance/frontend:main  # ✅ Pull from registry
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  uploads_data:
  postgres_data:
