"""Add usd_rate and status history

Revision ID: 3e81a2a81f5e
Revises: d2e59c8cfef1
Create Date: 2026-03-14 13:27:53.201300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e81a2a81f5e'
down_revision: Union[str, Sequence[str], None] = 'd2e59c8cfef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
