"""add_templates_to_project_and_member

Revision ID: 577f7e1717ee
Revises: 3e81a2a81f5e
Create Date: 2026-03-18 03:50:38.848033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577f7e1717ee'
down_revision: Union[str, Sequence[str], None] = '3e81a2a81f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe column addition for projects
    op.add_column('projects', sa.Column('templates', sa.JSON(), nullable=True))
    op.execute("UPDATE projects SET templates = '[]'")
    
    # Safe column addition for team_members
    op.add_column('team_members', sa.Column('templates', sa.JSON(), nullable=True))
    op.execute("UPDATE team_members SET templates = '[]'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'templates')
    op.drop_column('projects', 'templates')
    # ### end Alembic commands ###
