"""add_templates_to_project_and_member

Revision ID: 577f7e1717ee
Revises: 3e81a2a81f5e
Create Date: 2026-03-18 03:50:38.848033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577f7e1717ee'
down_revision: Union[str, Sequence[str], None] = '3e81a2a81f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_status_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expense_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.String(), nullable=True),
    sa.Column('changed_by_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expense_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_status_history_expense_id'), 'expense_status_history', ['expense_id'], unique=False)
    op.add_column('expense_requests', sa.Column('usd_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    
    # Safe column addition for projects
    op.add_column('projects', sa.Column('templates', sa.JSON(), nullable=True))
    op.execute("UPDATE projects SET templates = '[]'")
    op.alter_column('projects', 'templates', nullable=False)
    
    # Safe column addition for team_members
    op.add_column('team_members', sa.Column('templates', sa.JSON(), nullable=True))
    op.execute("UPDATE team_members SET templates = '[]'")
    op.alter_column('team_members', 'templates', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'templates')
    op.drop_column('projects', 'templates')
    op.drop_column('expense_requests', 'usd_rate')
    op.drop_index(op.f('ix_expense_status_history_expense_id'), table_name='expense_status_history')
    op.drop_table('expense_status_history')
    # ### end Alembic commands ###
