"""add_template_key_to_request

Revision ID: 8bcc483cf9ea
Revises: 577f7e1717ee
Create Date: 2026-03-18 03:54:16.519708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcc483cf9ea'
down_revision: Union[str, Sequence[str], None] = '577f7e1717ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_requests', sa.Column('template_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_requests', 'template_key')
    # ### end Alembic commands ###
