"""Initial migration

Revision ID: d2e59c8cfef1
Revises: 
Create Date: 2026-03-14 13:23:54.170057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e59c8cfef1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_counters',
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('project_code')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_login'), 'team_members', ['login'], unique=True)
    op.create_index(op.f('ix_team_members_status'), 'team_members', ['status'], unique=False)
    op.create_index(op.f('ix_team_members_telegram_chat_id'), 'team_members', ['telegram_chat_id'], unique=True)
    op.create_table('expense_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('receipt_photo_file_id', sa.String(), nullable=True),
    sa.Column('refund_data', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_by_position', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_code', sa.String(), nullable=True),
    sa.Column('internal_comment', sa.String(), nullable=True),
    sa.Column('status_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_requests_created_by_id'), 'expense_requests', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_date'), 'expense_requests', ['date'], unique=False)
    op.create_index(op.f('ix_expense_requests_project_id'), 'expense_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_expense_requests_request_id'), 'expense_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_expense_requests_request_type'), 'expense_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_expense_requests_status'), 'expense_requests', ['status'], unique=False)
    op.create_table('member_projects',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_projects')
    op.drop_index(op.f('ix_expense_requests_status'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_request_type'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_request_id'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_project_id'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_date'), table_name='expense_requests')
    op.drop_index(op.f('ix_expense_requests_created_by_id'), table_name='expense_requests')
    op.drop_table('expense_requests')
    op.drop_index(op.f('ix_team_members_telegram_chat_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_status'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_login'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('settings')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('project_counters')
    # ### end Alembic commands ###
